### PR TITLE
Center alignment, nice and clean

### PR DESCRIPTION
**Pull request by rdavid**
- Use div element.
- Use blank line after div:
 https://stackoverflow.com/questions/14051715/markdown-native-text-alignment
- Add new line at the end, it is a Unix text file.

### CODE REVIEW

**Comment by umputun** [comment]
will be nice to see before and after

**Comment by rdavid** [comment]
Screen Shot 2022-04-20 at 0 20 15
Before and after

**Comment by umputun** [comment]
this is a little bit inconsistent with other articles but still fine. thx

**Comment by umputun** [comment]
I guess you haven't check it in hugo, because it did nothing. I'll revert the merge

**Pull request merged**
